### ISSUE TITLE
Controller pods must be deleted and restarted to pick up new retention policy

### ISSUE THREAD

**Issue by bwmetcalf** [argoproj/argo-workflows#11194]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Using
```
% helm list -n argo
NAME          	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
argo-workflows	argo     	14      	2023-06-09 15:48:03.550419949 +0000 UTC	deployed	argo-workflows-0.28.2	v3.4.8
```
After making a change to the helm values and redeploying, the new retention policy settings do not take effect until the controller pods are deleted.  It seems the controller code should pick up the new configmap configuration automatically.  Perhaps it does but not in a timely manner?

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
We can see this from the output of `argo list`.  After updating the retention policy, the behavior remains the same until the controller pods are cycled.
```

### Logs from the workflow controller

```text
n/a
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by sarabala1979** [comment]
fixed in https://github.com/argoproj/argo-workflows/pull/10218

**Comment by sarabala1979** [comment]
can you try with `latest`

**Comment by bwmetcalf** [comment]
Thanks @sarabala1979!  We'll update and report back.  It looks like the code changes will indeed fix the issue.

**Comment by bwmetcalf** [comment]
@sarabala1979 Is there a release planned soon so we can move this fix to our production environments.  I haven't tried `latest` yet as we prefer to use tagged releases.  Just getting back from vacation and following up.  Thanks!

**Comment by bwmetcalf** [comment]
3.4.8 is the version we are using which exhibited the problem which led to me creating this issue.  I see https://github.com/argoproj/argo-workflows/pull/10218 was merged a while back, but it seems to have not fixed our issue.

**Comment by bwmetcalf** [comment]
It looks like some refactoring has taken place since the above MR as the code now lives here https://github.com/argoproj/argo-workflows/blob/dc56332e6a4de71dd0ec0af9bd8a2b9686e550b4/workflow/controller/controller.go#L406C4-L406C4 and is a bit different from the original MR.

**Comment by tooptoop4** [comment]
i think this can be closed, stakater/reloader handles this
