### ISSUE TITLE
Service Unavailable: connection error: desc = "transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property

### ISSUE THREAD

**Issue by yukikea** [argoproj/argo-workflows#14422]
### Pre-requisites

- [x] I have double-checked my configuration
- [x] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [x] I have searched existing issues and could not find a match for this bug
- [x] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

I started seeing `Service Unavailable: connection error: desc = "transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property. If you upgraded from a grpc-go version earlier than 1.67, your TLS connections may have stopped working due to ALPN enforcement. For more details, see: https://github.com/grpc/grpc-go/issues/434" on the UI.
` from this Tuesday after `argo-server` restarted not sure if that's the cause though.
We have an entire stack deployed via Metaflow so basically https://github.com/outerbounds/metaflow-tools/tree/master/gcp/terraform on our GCP project.

### Version(s)

fa87072583a04f5cc278379cd16778cec3607c822cf8efd6fed2f0f6b56a5bec

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflow that uses private images.

```YAML
We can't proceed with running any workflow at the moment. The above error is on UI https://localhost:2746/
```

### Logs from the workflow controller

```text
time="2025-04-23T23:40:21.379Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=474752098 namespace=argo workflow=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000
time="2025-04-23T23:40:21.379Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=29 workflow=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000
time="2025-04-23T23:40:21.382Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-26505037, taskName end"
time="2025-04-23T23:40:21.382Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-2567763576, taskName join"
time="2025-04-23T23:40:21.464Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-2567763576, taskName join"
time="2025-04-23T23:40:21.464Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-26505037, taskName end"
time="2025-04-23T23:40:21.464Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-2567763576, taskName join"
time="2025-04-23T23:40:21.464Z" level=warning msg="was unable to obtain the node for ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-26505037, taskName end"
time="2025-04-23T23:40:21.465Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000
time="2025-04-23T23:40:21.465Z" level=info msg=reconcileAgentPod namespace=argo workflow=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000
time="2025-04-23T23:40:21.466Z" level=info msg="Workflow to be dehydrated" Workflow Size=156137
time="2025-04-23T23:40:21.528Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=474752280 workflow=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000
time="2025-04-23T23:40:27Z" level=info msg="update pod event" pod=ffpfulfilmentforecast.prod.lightgbmpredict-1745451000-create-predictions-3205065359
```

### Logs from in your workflow's wait container

```text
No resources found in argo namespace.
```

**Comment by yukikea** [comment]
downgrading images to
- quay.io/argoproj/workflow-controller:latest|quay.io/argoproj/workflow-controller:v3.6.5
- quay.io/argoproj/argocli:latest|quay.io/argoproj/argocli:v3.6.5

fixed the issue for now

**Comment by Joibel** [comment]
You have downgraded from `latest` to `3.6.5`? Your last message is unclear.

**Comment by Joibel** [comment]
I've worked around this for 3.6 in #14433 and will make a 3.6.7 with that in. This is the wrong decision for the long term, and we should fix it properly. I'm unsure how to make the frontend make happily formed requests - @MasonM, do you know?

**Comment by yukikea** [comment]
> You have downgraded from `latest` to `3.6.5`? Your last message is unclear.

Yes

**Comment by Joibel** [comment]
This bug is present in 3.7.0-rc1.

There is a workaround in 3.6.7 which we attempted to fix in 3.6.9, but have gone back to the workaround in 3.6.10.

**Comment by prkhrkat** [comment]
Hey, I'm also getting the same error when upgrading my dependencies to 

```
        github.com/argoproj/argo-cd/v2 v2.14.13
	github.com/argoproj/argo-rollouts v1.8.2
	github.com/argoproj/argo-workflows/v3 v3.5.13
        google.golang.org/grpc v1.72.2
```
how to fix it?

**Comment by seenanadimi** [comment]
What is the current recommendation? I am still on v3.6.10 and still seeing this issue.

**Comment by Joibel** [comment]
> What is the current recommendation? I am still on v3.6.10 and still seeing this issue.

Open an issue explaining in detail how to reproduce it. As described above, this is fixed on 3.6.10 for me (and verified by others).

**Comment by youngdjn** [comment]
I am also seeing this issue in v3.6.10 (and it is still resolved by the env var hack). Here are my minimal steps to reproduce:

Argo install:
```
curl -sLO "https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/argo-linux-amd64.gz"
gunzip "argo-linux-amd64.gz"
chmod +x "argo-linux-amd64"
sudo mv "./argo-linux-amd64" /usr/local/bin/argo
kubectl create namespace argo
kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/namespace-install.yaml
argo server --auth-mode server -n argo
```

Then open the server at https://<server_ip>:2746

**Comment by Joibel** [comment]
> I am also seeing this issue in v3.6.10 (and it is still resolved by the env var hack). Here are my minimal steps to reproduce:
> 
> Argo install:
> 
> ```
> curl -sLO "https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/argo-linux-amd64.gz"
> gunzip "argo-linux-amd64.gz"
> chmod +x "argo-linux-amd64"
> sudo mv "./argo-linux-amd64" /usr/local/bin/argo
> kubectl create namespace argo
> kubectl apply -n argo -f https://github.com/argoproj/argo-workflows/releases/download/v3.6.10/namespace-install.yaml
> argo server --auth-mode server -n argo
> ```
> 
> Then open the server at https://<server_ip>:2746

You'll need to set the environment variable `GRPC_ENFORCE_ALPN_ENABLED=false` as per https://github.com/argoproj/argo-workflows/blob/62302816ff8de28bcb0f92fc5efd1915d130ef9d/Dockerfile#L127 and https://argo-workflows.readthedocs.io/en/latest/argo-server/#grpc-alpn

Do this before your final line where you run `argo server`

We could race the library and use a golang init() call to try and set it in go code, I haven't tried that.

**Comment by youngdjn** [comment]
Thank you @Joibel, and apologies for missing that docs page. I was under the impression from the above discussion that the environment variable hack was no longer required. But now I understand, and I'm glad this is working as expected. Thanks for all your work on this great tool.
