### ISSUE TITLE
Error in UI: `Connection closed to api/v1/workflow-events/argo?...`

### ISSUE THREAD

**Issue by kulmam92** [argoproj/argo-workflows#4804]
### What happened/what you expected to happen?

I exposed Argo Workflow UI using Ambassador under `/argo/` subpath. I was able to access the UI. However, I got `Unable to load data` error.
![01 forbidden](https://user-images.githubusercontent.com/4615942/103161843-fffa5c00-479c-11eb-8af7-3d3d7addb62b.png)

After that I got recurring "Connection closed to api/v1/workflow-events/argo?listOptions.resourceVersion=30237..." error.
![02 connection-closed](https://user-images.githubusercontent.com/4615942/103161854-2ae4b000-479d-11eb-8b2b-90b6cc5a31bf.png)
`Connection closed to api/v1/workflow-events/argo?listOptions.resourceVersion=7273&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.object.status.estimatedDuration,result.object.status.progress,result.type,result.object.metadata.labels,result.object.spec.suspend: 
`
## Diagnostics

What Kubernetes provider are you using?  
1.19.4
What version of Argo Workflows are you running? 
2.12.2

### Steps to reproduce

1. Create K3D cluster
```
k3d cluster create dev-ld --api-port 6443 -p 8080:80@loadbalancer --agents 2 \
    --k3s-server-arg '--flannel-backend=none' --k3s-server-arg '--no-deploy=traefik' \
    --volume "$(CURRENT_DIR)/k3d_custom/calico.yaml:/var/lib/rancher/k3s/server/manifests/calico.yaml"
```
2. Install Ambassador Edge Stack
```
kubectl apply -f https://www.getambassador.io/yaml/aes-crds.yaml && \
kubectl wait --for condition=established --timeout=90s crd -lproduct=aes && \
kubectl apply -f https://www.getambassador.io/yaml/aes.yaml && \
kubectl -n ambassador wait --for condition=available --timeout=90s deploy -lproduct=aes
```
3. Install metallb
metal-lb-layer2-config.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.0.3-172.18.0.254
```
```
# https://kubernetes.github.io/ingress-nginx/deploy/baremetal/
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.5/manifests/metallb.yaml
# On first install only
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
kubectl apply -f $(CURRENT_DIR)/k3d_custom/metal-lb-layer2-config.yaml
```
4. Configure tuntap - Mac only
```
# Install tuntap:
brew install Caskroom/cask/tuntap
# https://blog.kubernauts.io/k3s-with-k3d-and-metallb-on-mac-923a3255c36e
# only needed for Mac
# create a bridge interface between the Physical Machine and the Host Virtual Machine.
# download scripts form https://github.com/arashkaffamanesh/k3d-k3s-metallb
k3d cluster stop dev-ld
./k3d_custom/docker-tuntap-osx/sbin/docker_tap_install.sh
echo "Wait till docker is restarted."
sleep 40
echo "..done"
./k3d_custom/docker-tuntap-osx/sbin/docker_tap_up.sh
sudo route -v add -net 172.18.0.0 -netmask 255.255.255.0 10.0.75.2
k3d cluster start dev-ld
```
5. Install argo
```
kubectl create namespace argo || true
kubectl -n argo apply -f https://raw.githubusercontent.com/argoproj/argo/master/manifests/quick-start-postgres.yaml
# Since K3S uses containerd, you need to configure the workflow controller to use the PNS (Pod Namespace Sharing) executor
kubectl -n argo patch cm workflow-controller-configmap -p '{"data": {"containerRuntimeExecutor": "pns"}}';
kubectl -n argo wait pod -lapp=argo-server --for condition=available --timeout=180s
```
6. Patch argo
argocd-patch.yaml
```yaml
spec:
  template:
    spec:
      containers:
      - args:
        - server
        - --namespaced
        - --auth-mode
        - server
        - --auth-mode
        - client
        - --basehref
        - /argo/
        image: argoproj/argocli:latest
        name: argo-server
```
```
kubectl -n argo patch deployment/argo-server -p "$(cat argocd-patch.yaml)"
```
7. Create Ambassador mapping
argo-ingress-ambassador.yaml
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argo-server
  namespace: argo
spec:
  prefix: /argo/
  regex_rewrite:
    pattern: '/argo(/|$)(.*)'
    substitution: '/\2'
  service: argo-server:2746
```
```
kubectl -n argo apply -f resources/argo-ingress-ambassador.yaml
```
8. argo-server log
```
❯ kubectl -n argo logs argo-server-db794976-gchd2                                           
time="2020-12-27T05:06:17.892Z" level=info authModes="[server client]" baseHRef=/argo/ managedNamespace=argo namespace=argo secure=false
time="2020-12-27T05:06:17.893Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo/tls/"
time="2020-12-27T05:06:17.893Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-12-27T05:06:17.893Z" level=info msg="SSO disabled"
time="2020-12-27T05:06:18.061Z" level=info msg="Starting Argo Server" instanceID= version=764f118ca4180b476a9b053873e55eeccbc5e202
time="2020-12-27T05:06:18.062Z" level=info msg="Creating DB session"
time="2020-12-27T05:06:18.121Z" level=info msg="Node status offloading config" ttl=5m0s
time="2020-12-27T05:06:18.122Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2020-12-27T05:06:18.125Z" level=info msg="Argo Server started successfully on http://localhost:2746"
time="2020-12-27T05:10:23.551Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=37.122 span.kind=server system=grpc
time="2020-12-27T05:10:23.661Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflowtemplates.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot list resource \"workflowtemplates\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=81.194 span.kind=server system=grpc
time="2020-12-27T05:10:23.665Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = cronworkflows.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot list resource \"cronworkflows\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=81.08 span.kind=server system=grpc
time="2020-12-27T05:10:23.757Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = workflows.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo-server\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope" grpc.code=PermissionDenied grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=5.809 span.kind=server system=grpc
time="2020-12-27T05:10:23.917Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=0.886 span.kind=server system=grpc
time="2020-12-27T05:10:24.080Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=120.036 span.kind=server system=grpc
time="2020-12-27T05:10:24.090Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2020-12-27T05:10:23Z" grpc.time_ms=124.877 span.kind=server system=grpc
time="2020-12-27T05:10:24.150Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-12-27T05:10:24Z" grpc.time_ms=132.258 span.kind=server system=grpc
time="2020-12-27T05:10:27.242Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-12-27T05:10:24Z" grpc.time_ms=3000.936 span.kind=server system=grpc
time="2020-12-27T05:10:37.329Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-12-27T05:10:37Z" grpc.time_ms=15.356 span.kind=server system=grpc
time="2020-12-27T05:10:40.387Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-12-27T05:10:37Z" grpc.time_ms=2999.413 span.kind=server system=grpc
```
9. workflow-controller log
```
❯ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | more            
time="2020-12-27T05:08:33.189Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-12-27T05:08:33.233Z" level=info msg="Configuration:\nartifactRepository:\n  archiveLogs: true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: my-minio-cred\n    bucket: my-bucket\n    endpoint: minio:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: my-minio-cred\ncontainerRuntimeExecutor: pns\ninitialDelay: 0s\nlinks:\n- name: Example Workflow Link\n  scope: workflow\n  url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Example Pod Link\n  scope: pod\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\nmetricsConfig:\n  disableLegacy: true\n  enabled: true\n  path: /metrics\n  port: 9090\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveTTL: 168h0m0s\n  connectionPool:\n    maxIdleConns: 100\n  nodeStatusOffLoad: true\n  postgresql:\n    database: postgres\n    host: postgres\n    passwordSecret:\n      key: password\n      name: argo-postgres-config\n    port: 5432\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-postgres-config\npodSpecLogStrategy: {}\ntelemetryConfig: {}\n"
:...skipping...
time="2020-12-27T05:08:33.189Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-12-27T05:08:33.233Z" level=info msg="Configuration:\nartifactRepository:\n  archiveLogs: true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: my-minio-cred\n    bucket: my-bucket\n    endpoint: minio:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: my-minio-cred\ncontainerRuntimeExecutor: pns\ninitialDelay: 0s\nlinks:\n- name: Example Workflow Link\n  scope: workflow\n  url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\n- name: Example Pod Link\n  scope: pod\n  url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}\nmetricsConfig:\n  disableLegacy: true\n  enabled: true\n  path: /metrics\n  port: 9090\nnodeEvents: {}\npersistence:\n  archive: true\n  archiveTTL: 168h0m0s\n  connectionPool:\n    maxIdleConns: 100\n  nodeStatusOffLoad: true\n  postgresql:\n    database: postgres\n    host: postgres\n    passwordSecret:\n      key: password\n      name: argo-postgres-config\n    port: 5432\n    tableName: argo_workflows\n    userNameSecret:\n      key: username\n      name: argo-postgres-config\npodSpecLogStrategy: {}\ntelemetryConfig: {}\n"
time="2020-12-27T05:08:33.233Z" level=info msg="Persistence configuration enabled"
time="2020-12-27T05:08:33.234Z" level=info msg="Creating DB session"
time="2020-12-27T05:08:33.257Z" level=info msg="Persistence Session created successfully"
time="2020-12-27T05:08:33.265Z" level=info msg="Migrating database schema" clusterName=default dbType=postgres
time="2020-12-27T05:08:33.275Z" level=info msg="applying database change" change="create table if not exists argo_workflows (\n    id varchar(128) ,\n    name varchar(256),\n    phase varchar(25),\n    namespace varchar(256),\n    workflow text,\n    startedat timestamp default CURRENT_TIMESTAMP,\n    finishedat timestamp default CURRENT_TIMESTAMP,\n    primary key (id, namespace)\n)" changeSchemaVersion=0
time="2020-12-27T05:08:33.286Z" level=info msg="applying database change" change="create unique index idx_name on argo_workflows (name)" changeSchemaVersion=1
time="2020-12-27T05:08:33.295Z" level=info msg="applying database change" change="create table if not exists argo_workflow_history (\n    id varchar(128) ,\n    name varchar(256),\n    phase varchar(25),\n    namespace varchar(256),\n    workflow text,\n    startedat timestamp default CURRENT_TIMESTAMP,\n    finishedat timestamp default CURRENT_TIMESTAMP,\n    primary key (id, namespace)\n)" changeSchemaVersion=2
time="2020-12-27T05:08:33.304Z" level=info msg="applying database change" change="alter table argo_workflow_history rename to argo_archived_workflows" changeSchemaVersion=3
time="2020-12-27T05:08:33.310Z" level=info msg="applying database change" change="drop index idx_name" changeSchemaVersion=4
time="2020-12-27T05:08:33.315Z" level=info msg="applying database change" change="create unique index idx_name on argo_workflows(name, namespace)" changeSchemaVersion=5
time="2020-12-27T05:08:33.321Z" level=info msg="applying database change" change="alter table argo_workflows drop constraint argo_workflows_pkey" changeSchemaVersion=6
time="2020-12-27T05:08:33.326Z" level=info msg="applying database change" change="alter table argo_workflows add primary key(name,namespace)" changeSchemaVersion=7
time="2020-12-27T05:08:33.331Z" level=info msg="applying database change" change="alter table argo_archived_workflows drop constraint argo_workflow_history_pkey" changeSchemaVersion=8
time="2020-12-27T05:08:33.335Z" level=info msg="applying database change" change="alter table argo_archived_workflows add primary key(id)" changeSchemaVersion=9
time="2020-12-27T05:08:33.342Z" level=info msg="applying database change" change="alter table argo_archived_workflows rename column id to uid" changeSchemaVersion=10
time="2020-12-27T05:08:33.345Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column uid set not null" changeSchemaVersion=11
time="2020-12-27T05:08:33.351Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column phase set not null" changeSchemaVersion=12
time="2020-12-27T05:08:33.356Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column namespace set not null" changeSchemaVersion=13
time="2020-12-27T05:08:33.360Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column workflow set not null" changeSchemaVersion=14
time="2020-12-27T05:08:33.365Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column startedat set not null" changeSchemaVersion=15
time="2020-12-27T05:08:33.370Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column finishedat set not null" changeSchemaVersion=16
time="2020-12-27T05:08:33.374Z" level=info msg="applying database change" change="alter table argo_archived_workflows add clustername varchar(64)" changeSchemaVersion=17
time="2020-12-27T05:08:33.378Z" level=info msg="applying database change" change="update argo_archived_workflows set clustername = 'default' where clustername is null" changeSchemaVersion=18
time="2020-12-27T05:08:33.381Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column clustername set not null" changeSchemaVersion=19
time="2020-12-27T05:08:33.384Z" level=info msg="applying database change" change="alter table argo_archived_workflows drop constraint argo_archived_workflows_pkey" changeSchemaVersion=20
time="2020-12-27T05:08:33.390Z" level=info msg="applying database change" change="alter table argo_archived_workflows add primary key(clustername,uid)" changeSchemaVersion=21
time="2020-12-27T05:08:33.395Z" level=info msg="applying database change" change="create index argo_archived_workflows_i1 on argo_archived_workflows (clustername,namespace)" changeSchemaVersion=22
time="2020-12-27T05:08:33.405Z" level=info msg="applying database change" change="alter table argo_workflows drop column phase" changeSchemaVersion=23
time="2020-12-27T05:08:33.409Z" level=info msg="applying database change" change="alter table argo_workflows drop column startedat" changeSchemaVersion=24
time="2020-12-27T05:08:33.412Z" level=info msg="applying database change" change="alter table argo_workflows drop column finishedat" changeSchemaVersion=25
time="2020-12-27T05:08:33.415Z" level=info msg="applying database change" change="alter table argo_workflows rename column id to uid" changeSchemaVersion=26
time="2020-12-27T05:08:33.419Z" level=info msg="applying database change" change="alter table argo_workflows alter column uid set not null" changeSchemaVersion=27
time="2020-12-27T05:08:33.422Z" level=info msg="applying database change" change="alter table argo_workflows alter column namespace set not null" changeSchemaVersion=28
time="2020-12-27T05:08:33.425Z" level=info msg="applying database change" change="alter table argo_workflows add column clustername varchar(64)" changeSchemaVersion=29
time="2020-12-27T05:08:33.429Z" level=info msg="applying database change" change="update argo_workflows set clustername = 'default' where clustername is null" changeSchemaVersion=30
time="2020-12-27T05:08:33.432Z" level=info msg="applying database change" change="alter table argo_workflows alter column clustername set not null" changeSchemaVersion=31
time="2020-12-27T05:08:33.436Z" level=info msg="applying database change" change="alter table argo_workflows add column version varchar(64)" changeSchemaVersion=32
time="2020-12-27T05:08:33.440Z" level=info msg="applying database change" change="alter table argo_workflows add column nodes text" changeSchemaVersion=33
time="2020-12-27T05:08:33.443Z" level=info msg="applying database change" change="backfillNodes{argo_workflows}" changeSchemaVersion=34
time="2020-12-27T05:08:33.443Z" level=info msg="Backfill node status"
time="2020-12-27T05:08:33.447Z" level=info msg="applying database change" change="alter table argo_workflows alter column nodes set not null" changeSchemaVersion=35
time="2020-12-27T05:08:33.450Z" level=info msg="applying database change" change="alter table argo_workflows drop column workflow" changeSchemaVersion=36
time="2020-12-27T05:08:33.454Z" level=info msg="applying database change" change="alter table argo_workflows add column updatedat timestamp not null default current_timestamp" changeSchemaVersion=37
time="2020-12-27T05:08:33.457Z" level=info msg="applying database change" change="alter table argo_workflows drop constraint argo_workflows_pkey" changeSchemaVersion=38
time="2020-12-27T05:08:33.462Z" level=info msg="applying database change" change="drop index idx_name" changeSchemaVersion=39
time="2020-12-27T05:08:33.466Z" level=info msg="applying database change" change="alter table argo_workflows drop column name" changeSchemaVersion=40
time="2020-12-27T05:08:33.470Z" level=info msg="applying database change" change="alter table argo_workflows add primary key(clustername,uid,version)" changeSchemaVersion=41
time="2020-12-27T05:08:33.475Z" level=info msg="applying database change" change="create index argo_workflows_i1 on argo_workflows (clustername,namespace)" changeSchemaVersion=42
time="2020-12-27T05:08:33.482Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column workflow type json using workflow::json" changeSchemaVersion=43
time="2020-12-27T05:08:33.496Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column name set not null" changeSchemaVersion=44
time="2020-12-27T05:08:33.506Z" level=info msg="applying database change" change="create index argo_workflows_i2 on argo_workflows (clustername,namespace,updatedat)" changeSchemaVersion=45
time="2020-12-27T05:08:33.512Z" level=info msg="applying database change" change="create table if not exists argo_archived_workflows_labels (\n\tclustername varchar(64) not null,\n\tuid varchar(128) not null,\n    name varchar(317) not null,\n    value varchar(63) not null,\n    primary key (clustername, uid, name),\n \tforeign key (clustername, uid) references argo_archived_workflows(clustername, uid) on delete cascade\n)" changeSchemaVersion=46
time="2020-12-27T05:08:33.523Z" level=info msg="applying database change" change="alter table argo_workflows alter column nodes type json using nodes::json" changeSchemaVersion=47
time="2020-12-27T05:08:33.536Z" level=info msg="applying database change" change="alter table argo_archived_workflows add column instanceid varchar(64)" changeSchemaVersion=48
time="2020-12-27T05:08:33.540Z" level=info msg="applying database change" change="update argo_archived_workflows set instanceid = '' where instanceid is null" changeSchemaVersion=49
time="2020-12-27T05:08:33.545Z" level=info msg="applying database change" change="alter table argo_archived_workflows alter column instanceid set not null" changeSchemaVersion=50
time="2020-12-27T05:08:33.550Z" level=info msg="applying database change" change="drop index argo_archived_workflows_i1" changeSchemaVersion=51
time="2020-12-27T05:08:33.555Z" level=info msg="applying database change" change="create index argo_archived_workflows_i1 on argo_archived_workflows (clustername,instanceid,namespace)" changeSchemaVersion=52
time="2020-12-27T05:08:33.562Z" level=info msg="applying database change" change="drop index argo_workflows_i1" changeSchemaVersion=53
time="2020-12-27T05:08:33.566Z" level=info msg="applying database change" change="drop index argo_workflows_i2" changeSchemaVersion=54
time="2020-12-27T05:08:33.571Z" level=info msg="applying database change" change="create index argo_workflows_i1 on argo_workflows (clustername,namespace,updatedat)" changeSchemaVersion=55
time="2020-12-27T05:08:33.577Z" level=info msg="applying database change" change="create index argo_archived_workflows_i2 on argo_archived_workflows (clustername,instanceid,finishedat)" changeSchemaVersion=56
time="2020-12-27T05:08:33.582Z" level=info msg="Node status offloading config" ttl=5m0s
time="2020-12-27T05:08:33.582Z" level=info msg="Node status offloading is enabled"
time="2020-12-27T05:08:33.583Z" level=info msg="Workflow archiving is enabled"
time="2020-12-27T05:08:33.585Z" level=info msg="Starting Workflow Controller" version=764f118ca4180b476a9b053873e55eeccbc5e202
time="2020-12-27T05:08:33.585Z" level=info msg="Workers: workflow: 32, pod: 32, pod cleanup: 4"
time="2020-12-27T05:08:33.771Z" level=info msg="Manager initialized successfully"
I1227 05:08:33.774426       1 leaderelection.go:242] attempting to acquire leader lease  argo/workflow-controller...
I1227 05:08:33.792510       1 leaderelection.go:252] successfully acquired lease argo/workflow-controller
time="2020-12-27T05:08:33.792Z" level=info msg="new leader" id=workflow-controller-75cb95b89d-6l49r leader=workflow-controller-75cb95b89d-6l49r
time="2020-12-27T05:08:33.793Z" level=info msg="started leading" id=workflow-controller-75cb95b89d-6l49r
time="2020-12-27T05:08:33.793Z" level=info msg="Performing periodic GC every 5m0s"
time="2020-12-27T05:08:33.793Z" level=info msg="Performing archived workflow GC" periodicity=24h0m0s ttl=604800000000000
time="2020-12-27T05:08:33.799Z" level=info msg="Starting workflow TTL controller (resync 20m0s, workflowTTLWorkers 4)"
time="2020-12-27T05:08:33.799Z" level=info msg="Started workflow TTL worker"
time="2020-12-27T05:08:33.801Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2020-12-27T05:08:33.805Z" level=info msg="Starting CronWorkflow controller"
time="2020-12-27T05:13:32.973Z" level=info msg="Alloc=5797 TotalAlloc=22882 Sys=70080 NumGC=8 Goroutines=201"
time="2020-12-27T05:13:33.581Z" level=info msg="Performing periodic workflow GC"
time="2020-12-27T05:13:33.593Z" level=info msg="Zero old offloads, nothing to do"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
It appears that you do not have permission to access the UI. That is normal, but you should have been redirected to /login. Can you confirm if that was the case or not please?

**Comment by kulmam92** [comment]
@alexec I wasn't redirected to /login. It stayed on the same page and got "Connection closed to api/v1/workflow-events/argo?listOptions.resourceVersion=30237..." error.

**Comment by alexec** [comment]
Can you try in Incognito mode?

**Comment by kulmam92** [comment]
Still same with Incognito mode.
![image](https://user-images.githubusercontent.com/4615942/103317781-0da02380-49e1-11eb-8b95-7cd2e7a9eab2.png)

**Comment by alexec** [comment]
can you see if you can login at HTTP://172.18.0.4/argo/login?

**Comment by kulmam92** [comment]
This is what I get when I go to http://172.18.0.4/argo/login.
![image](https://user-images.githubusercontent.com/4615942/103319312-3f67b900-49e6-11eb-9e54-dad62ec6cbe7.png)

The argo server is configure to use [server client] auth modes.
`level=info authModes="[server client]"
`

I got this when I ran auth token command.
```
❯ argo auth token
FATA[2020-12-29T15:05:34.965Z] could not find a token
```

If I click "LOGIN" under, client authentication with a blank auth token, it directed me to the https://172.18.0.4/argo/workflows/argo page and got the same error messages.
![image](https://user-images.githubusercontent.com/4615942/103319863-30820600-49e8-11eb-8e63-d397d3259eef.png)

**Comment by sylock** [comment]
I have the same issue with v2.12.4. If I check the web console I get a 503 timeout (after 30 sec) on this request:
```
https://<HOSTNAME>/api/v1/workflow-events/?listOptions.resourceVersion=20072688&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.object.status.estimatedDuration,result.object.status.progress,result.type,result.object.metadata.labels,result.object.spec.suspend
```

The argo logs log this line at the moment I get the timeout:
```
time="2021-01-15T19:39:12.455Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-01-15T19:38:42Z" grpc.time_ms=29864.176 span.kind=server system=grpc
```

**Comment by alexec** [comment]
Can you please try with `:latest`?

**Comment by syedshameersarwar** [comment]
Facing the same issue, tried both v2.12.3 and v2.12.4. I also increased the ambassador request timeout from 3000ms to 10000ms, but the issue is still there.

**Comment by alexec** [comment]
Could you please try with `argoproj/argocli:latest`?

**Comment by alexec** [comment]
I believe this is fixed in v3.0. Closing.

**Comment by sylock** [comment]
I don't see any v3.0 branch or release: https://github.com/argoproj/argo/releases

**Comment by dimoes** [comment]
Do you have the link to the fix?

**Comment by jaketsuyemura** [comment]
Experiencing the exact same issue using `v2.12.6`. Also tried with `latest` with the same results. Using ambassador hosted on Azure AKS.

Did not experience this issue on minikube with no Ambassador present.

**Comment by vic-c137** [comment]
Also experiencing the same issue on `v2.12.7` which is `latest` at the time of posting. @alexec can you point to a PR where you believe the fix exists?

**Comment by alexec** [comment]
This is not fixed in v3.0, but it appears the problem only occurs when a proxy is in front of the server.

Typically proxies (e.g. Nginx/Apache) disconnect the event-stream and need configuring with longer keep-alive timeouts.

https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

**Comment by vic-c137** [comment]
Thank you for this info @alexec! We'll investigate our proxy config.

**Comment by MadsHT** [comment]
https://github.com/argoproj/argo-workflows/issues/4804

https://stackoverflow.com/questions/58560048/sse-broken-after-deploying-with-kubernetes-and-connecting-via-ingress

**Comment by michaeldebouver** [comment]
I am still facing this issue, even by reconfiguring nginx.

**Comment by wnagele** [comment]
@alexec you are correct that this happens in scenarios where there is some sort of middleware (load balancer, etc.) present. However, this is a *lot* of deployments in production I would assume. I did some research and the underlying cause is in the way Argo deals with streaming events.

[Here](https://github.com/argoproj/argo-workflows/blob/master/server/workflow/workflow_server.go#L217) you open an event source stream but will only send back something if the K8S watch returns anything. Which could be a long time - or never. This will cause timeouts to trigger as no data is exchanged on that connection. This leaves the only workaround/hack right now to increase such timeouts in all your middleware - that is very bad though, since it also makes scalability and being open to attack more of a problem as you end up holding much more state. Also, it never really resolves the problem - it just pushes the problem out far enough for most users to not notice.

Websockets, etc. deal with this on the protocol level. But since you are using EventSource it is on you to ensure such "keep alives" are performed on the application data channel. The event stream format allows you to quite easily send a comment to achieve just that (see: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format).

**Comment by alexec** [comment]
This should fixed in v3. Please can you test to see?

**Comment by wnagele** [comment]
Any pointers where this was fixed in v3?

**Comment by chtcvl** [comment]
Still facing the issue in v3.0.0.

**Comment by alexec** [comment]
Can you try latest and see if it fixed there it might be the fix didn’t make v3

**Comment by chtcvl** [comment]
Tried running on latest, the issue looks resolved, thanks.
argo version used:
```
argo: untagged
  BuildDate: 2021-04-01T17:09:34Z
  GitCommit: 4e450e250168e6b4d51a126b784e90b11a0162bc
  GitTreeState: clean
  GitTag: untagged
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
```

**Comment by NightmareCinema** [comment]
@alexec Issue still persists in `v3.0.2` when using GKE's built-in Ingress controller.
Even attempting to lower/increase the `BackendConfig` resource `timeout` field proved not to make a difference.

**Comment by rajatvig** [comment]
Using v3.0.4 and it still persists

**Comment by luckyswede** [comment]
Hi,
I'm using 3.2.4 and I face a very similar issue. The call to 
```
api/v1/workflow-events/argo?listOptions.resourceVersion=3924263&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.creationTimestamp,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.message,result.object.status.startedAt,result.object.status.estimatedDuration,result.object.status.progress,result.type,result.object.metadata.labels,result.object.spec.suspend
```
hangs indefinitely, which means that the workflow info page is empty.
It started to happen after I put argo-server behind an nginx reverse proxy and added the BASE_HREF=/argo/ environment variable.
Other api calls seems to work fine.

**Comment by mxm-tr** [comment]
@luckyswede in case you are still on it, got it working by adding the configuration mentioned in the previous comment in my reverse proxy!

> This is not fixed in v3.0, but it appears the problem only occurs when a proxy is in front of the server.
> 
> Typically proxies (e.g. Nginx/Apache) disconnect the event-stream and need configuring with longer keep-alive timeouts.
> 
> https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

**Comment by luckyswede** [comment]
@mxm-tr yay, that worked, thanks! I havent tried it but I guess it's turning off chunked that is what matters

**Comment by asafhm** [comment]
Is there any solution for those who use GCE ingress controller on GKE?

**Comment by MattHodge** [comment]
FWIW, also not working with the [Azure Application Gateway Ingress Controller](https://github.com/Azure/application-gateway-kubernetes-ingress). I also tried with disabling proxy buffers as per this document: https://docs.microsoft.com/en-us/azure/application-gateway/proxy-buffers.

**Comment by knkski** [comment]
I encountered this issue with Argo 3.3.1 while using [Contour](https://projectcontour.io/) with its support for the [Gateway API](https://gateway-api.sigs.k8s.io/). I was unable to figure out how to make it work while using the `HTTPRoute` resource from the Gateway API specification, because it makes configuring timeouts [implementation specific](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/), and I don't think Contour has implemented anything yet. However, it turns out that Contour lets you mix and match `HTTPRoute`s from the Gateway API spec and their own `HTTPProxy` resources, and I was able to get rid of this message with an `HTTPProxy` like this:

```yaml
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argo-server
  namespace: argo
spec:
  routes:
  - services:
    - name: argo-server
      port: 2746
    timeoutPolicy:
      response: 300s
      idle: 300s
```

**Comment by niqdev** [comment]
I have the same issue in `v3.3.8` with Ambassador `3.0.0`. If it can help, I've temporarily "patched" it by increasing the timeout too
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argo-workflows-mapping
  labels:
    emissaryHost: emissary-host
spec:
  hostname: "argo-workflows.{{ .Values.hostname }}"
  prefix: /
  service: argo-workflows-server.argo:2746
  # argo-workflows uses eventsource https://developer.mozilla.org/en-US/docs/Web/API/EventSource
  # see https://www.getambassador.io/docs/emissary/latest/topics/using/timeouts
  timeout_ms: 300000 # 5 minutes, default is 3000 (3 seconds)
  connect_timeout_ms: 300000 # 5 minutes, cannot be disabled
```
I've opened a feature request 🤞🏻 https://github.com/emissary-ingress/emissary/issues/4323

**Comment by pergeri** [comment]
Any smart person managed to fix this with azure frontdoor? Having the same issue with multiple versions but guessing its because of something like the nginx-proxy.

**Comment by groteck** [comment]
I'm getting this error with the QuickStart guide not sure what I'm missing here.

**Comment by aobitubewefox** [comment]
I am still getting the issue when using Emissary and Argo Workflows version 3.4.0

**Comment by chadkouse** [comment]
for GKE to honor this timeout, you have to annotate your service to indicate the backendconfig to use.  See the [Docs](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#associating_backendconfig_with_your_ingress)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-server
  annotations:
    networking.gke.io/managed-certificates: argo
spec:
  defaultBackend:
    service:
      name: argo-server
      port:
        number: 2746
---
kind: BackendConfig
metadata:
  name: config-argo-server
spec:
  timeoutSec: 86400
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: v1
kind: Service
metadata:
  name: argo-server
  annotations:
    cloud.google.com/backend-config: '{"default": "config-argo-server"}' # this is the annotation needed
spec:
  selector:
    app: argo-server
  ports:
  - name: web
    port: 2746
    targetPort: 2746
```

This was difficult for me to find so I hope it helps someone!

**Comment by TapTap21** [comment]
Can we reopen this issue? I am facing the same issue on EKS using AWS load balancer controller @alexec

**Comment by bhuddlestonocl** [comment]
Ran into this issue. Turned out to be that the service account created for logging into Workflows didn't have access to get and list pods + pod logs.

**Comment by Jonilei** [comment]
I meet this problem when i use istio proxy. Is there any solutions for istio proxy? How can i config gateway, or servicevitural, or DestinationRule resources?
