### ISSUE TITLE
Passing 'outputs.result' parameter through multiple workflows cause 'could not be parsed as a JSON list'

### ISSUE THREAD

**Issue by mhehle** [argoproj/argo-workflows#5097]
## Summary 

**Given is following workflow:**
Step1 generates a string value and outputs it as json string array on stdout.
Step2 reads output result from Step1 (steps.step1.outputs.results) and outputs it again as json string array on stdout.
Step3 reads output result from Step2 (steps.step2.outputs.results) and outputs it again as json string array on stdout. 

Step2 works as expected and prints out input from Step1.
Step3 failes with error message 'withParam value could not be parsed as a JSON list: {{tasks.echo2.outputs.result}}'

**Expected behaviour:**
Step3 should output input from Step2 like Step2 did it in previous step.

## Diagnostics

**What Kubernetes provider are you using?** 
Minikube (v1.17.1, Kubernetes v1.20.2)

**What version of Argo Workflows are you running?** 
v2.12.8 (latest)

**Paste a workflow that reproduces the bug, including status:**
```yaml
metadata:
  generateName: workflow-example-
  namespace: argo
spec:
  entrypoint: workflow-start
  templates:
    - name: workflow-start
      dag:
        tasks:
          - name: echo-message
            template: static-echo

          - name: grab-message-and-echo
            dependencies: [ echo-message ]
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withParam: "{{tasks.echo-message.outputs.result}}"          

          - name: grab-message-and-echo2
            dependencies: [ grab-message-and-echo ]
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{item}}"
            withParam: "{{tasks.grab-message-and-echo.outputs.result}}"

    - name: static-echo
      container:
        image: alpine:3.7
        command: [echo, "[\"this is a message\"]"]

    - name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.7
        command: [echo, "[\"{{inputs.parameters.message}}\"]"]
```

**Argo CLI result output**
```shell
Name:                workflow-example-4dl79
Namespace:           argo
ServiceAccount:      workflow
Status:              Error
Conditions:          
 Completed           True
Created:             Fri Feb 12 15:31:08 +0100 (20 seconds ago)
Started:             Fri Feb 12 15:31:08 +0100 (20 seconds ago)
Finished:            Fri Feb 12 15:31:28 +0100 (now)
Duration:            20 seconds
Progress:            2/2
ResourcesDuration:   2s*(1 cpu),2s*(100Mi memory)

STEP                             TEMPLATE        PODNAME                            DURATION  MESSAGE
 ⚠ workflow-example-4dl79        workflow-start                                                                                                                                   
 ├─✔ echo-message                        static-echo     workflow-example-4dl79-4275517793  3s                                                                                            
 ├─✔ grab-message-and-echo(0:this is a message)  echo            workflow-example-4dl79-1432846826  3s                                                                                            
 └─⚠ grab-message-and-echo2                       echo                                                         withParam value could not be parsed as a JSON list: {{tasks.echo2.outputs.result}}
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Could be fixed in 2.12.9

**Comment by mhehle** [comment]
> Could be fixed in 2.12.9

thanks, i will test it out in the next version

**Comment by alexec** [comment]
Can you try with :latest?

**Comment by mhehle** [comment]
> Can you try with :latest?

tested it on current master branch. The result now is different

### Variant 1: keep workflow template command
`command: [echo, "[\"{{inputs.parameters.message}}\"]"]`

**Steps with output:**
1. echo-message -> `["message is a message"]`
2. grab-echo -> `["message is a message"]`
3. grab-echo2 -> `["["this is a message"]"]`

another 4. step would fail due to invalid json.

### Variant 2: change workflow template command
`command: [echo, "{{inputs.parameters.message}}"]`

**Steps with output:**
1. echo-message -> `["message is a message"]`
2. grab-echo -> `message is a message`
3. grab-echo2 -> `invalid character 'h' in literal true (expecting 'r')`

**Comment by simster7** [comment]
@alexec Is this fixed by #5076? Close?

**Comment by alexec** [comment]
@mhehle I'm not clear from your last comment if you think this is an issue anymore?

**Comment by zxpower** [comment]
I'm noticing the same in v2.12.11. Trying to run following workflow and when `subtask` tries to execute then `when:` clause kills it with `invalid character 'a' in literal true (expecting 'r')` (as well I got `invalid character 'i' looking for beginning of value` in similar workflow, but again it happened while evaluating `when:` that contained output from dependent task).

Here is workflow.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-test-
spec:
  entrypoint: root
  arguments:
    parameters:
    - name: suppliers
      value: |
        [
          {"supplier_id":1},
          {"supplier_id":2},
          {"supplier_id":3},
          {"supplier_id":4}
        ]
  templates:
  - name: main
    activeDeadlineSeconds: 1800
    retryStrategy:
      retryPolicy: "Always"
      limit: 2
    inputs: &inputs
      parameters:
      - name: command
      - name: step_name
      - name: supplier_id
    container: &container
      terminationMessagePolicy: FallbackToLogsOnError
      image: alpine:3.14
      command: [sh, -c]
      args: [ "{{inputs.parameters.command}}" ]
    metadata: &metadata
      labels:
        workflow-step: "dag-test.{{inputs.parameters.step_name}}"
        supplier-id: "dag-test.{{inputs.parameters.supplier_id}}"

  - name: python
    activeDeadlineSeconds: 1800
    inputs: *inputs
    script: &script
      image: python:alpine3.14
      command: [python]
      source: |
        import random
        result = "False" if random.randint(0,1) == 0 else "True"
        print(result)
    metadata: *metadata

  - name: python-subpoint
    activeDeadlineSeconds: 1800
    inputs: *inputs
    script: 
      <<: *script
      source: |
        print(f'task_metadata-last_updated-True-2021-08-03 23:39:46')
    metadata: *metadata

  - name: do-supplier-tasks
    inputs: 
      parameters:
      - name: supplier
    dag:
      failFast: false
      tasks:
      - name: checkpoint
        template: python-subpoint
        arguments:
          parameters:
          - name: command
            value: ""
          - name: step_name
            value: checkpoint
          - name: supplier_id
            value: '{{item.supplier_id}}'
        withParam: "[{{inputs.parameters.supplier}}]"

      - name: subpoint
        dependencies: [ checkpoint ]
        when: "'{{tasks.checkpoint.outputs.result}}' =~ 'task_metadata-last_updated-True'"
        template: main
        arguments:
          parameters:
          - name: command
            value: |
              echo "you have reached subpoint"
          - name: step_name
            value: subpoint
          - name: supplier_id
            value: '{{item.supplier_id}}'
        withParam: "[{{inputs.parameters.supplier}}]"

  - name: do-suppliers
    dag:
      failFast: false
      tasks:
      - name: supplier-stuff
        template: do-supplier-tasks
        arguments:
          parameters:
          - name: supplier
            value: |
              {{item}}
        withParam: "{{workflow.parameters.suppliers}}"

  - name: root
    dag:
      failFast: false
      tasks:
      - name: first-task
        template: python
        arguments:
          parameters:
          - name: command
            value: ""
          - name: step_name
            value: first-task
          - name: supplier_id
            value: global

      - name: second-task
        dependencies: [ "first-task" ]
        when: "'{{tasks.first-task.outputs.result}}' =~ 'False'"
        template: main
        arguments:
          parameters:
          - name: command
            value: |
              echo "second-task"
          - name: step_name
            value: second-task
          - name: supplier_id
            value: global

      - name: supplier
        template: do-suppliers
```

**Comment by zxpower** [comment]
Updated Argo to v3.1.6 and still getting the same error with YAML above:

```
Name:                dag-test-q6frs
Namespace:           argo-run
ServiceAccount:      default
Status:              Error
Conditions:
 PodRunning          False
 Completed           True
Created:             Tue Aug 24 13:16:02 +0300 (20 seconds ago)
Started:             Tue Aug 24 13:16:02 +0300 (20 seconds ago)
Finished:            Tue Aug 24 13:16:22 +0300 (now)
Duration:            20 seconds
Progress:            6/6
ResourcesDuration:   29s*(1 cpu),29s*(100Mi memory)
Parameters:
  suppliers:         [
  {"supplier_id":1},
  {"supplier_id":2},
  {"supplier_id":3},
  {"supplier_id":4}
]


STEP                                    TEMPLATE           PODNAME                    DURATION  MESSAGE
 ⚠ dag-test-q6frs                       root
 ├─✔ first-task                         python             dag-test-q6frs-2082196011  6s
 ├─⚠ supplier                           do-suppliers
 │ ├─⚠ supplier-stuff(0:supplier_id:1)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:1)    python-subpoint    dag-test-q6frs-451117948   8s
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ ├─⚠ supplier-stuff(1:supplier_id:2)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:2)    python-subpoint    dag-test-q6frs-3895089929  10s
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ ├─⚠ supplier-stuff(2:supplier_id:3)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:3)    python-subpoint    dag-test-q6frs-2788095174  9s
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ └─⚠ supplier-stuff(3:supplier_id:4)  do-supplier-tasks
 │   ├─✔ checkpoint(0:supplier_id:4)    python-subpoint    dag-test-q6frs-1424219283  9s
 │   └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 └─✔ second-task(0)                     main               dag-test-q6frs-2373620330  6s
 ```

Also getting following error `invalid character 'i' looking for beginning of value` while running similar workflow on the same level as `subpoint`. But as soon as I'm commenting out `when: "'{{tasks.checkpoint.outputs.result}}' =~ 'task_metadata-last_updated-True'"` line in workflow above or similar `when:` line in other workflow - things start to work.

I created a Go program to evaluate the same `when` logic with [Govaluate](https://github.com/Knetic/govaluate) and there was no issues. All examples checked out OK, so it looks like it's an issue with using `outputs.result` in `when` clause if the step relies on `withParam`.

Any thoughts @alexec ?

**Comment by zxpower** [comment]
Another update - added additional substep to workflow above between `checkpoint` and `subpoint` to mimic more our environment:

```
      - name: another-subpoint
        dependencies:
        - checkpoint
        template: main
        arguments:
          parameters:
          - name: command
            value: |
              echo "you have reached another subpoint: {{item.supplier_id}}"
          - name: step_name
            value: another-subpoint
          - name: supplier_id
            value: '{{item.supplier_id}}'
        withParam: "[{{inputs.parameters.supplier}}]"
```

And got following result:

```
Name:                dag-test-bqz82
Namespace:           argo-run
ServiceAccount:      default
Status:              Error
Conditions:
 PodRunning          False
 Completed           True
Created:             Tue Aug 24 13:56:54 +0300 (20 seconds ago)
Started:             Tue Aug 24 13:56:54 +0300 (20 seconds ago)
Finished:            Tue Aug 24 13:57:14 +0300 (now)
Duration:            20 seconds
Progress:            6/6
ResourcesDuration:   18s*(1 cpu),18s*(100Mi memory)
Parameters:
  suppliers:         [
  {"supplier_id":1},
  {"supplier_id":2},
  {"supplier_id":3},
  {"supplier_id":4}
]


STEP                                    TEMPLATE           PODNAME                    DURATION  MESSAGE
 ⚠ dag-test-bqz82                       root
 ├─✔ first-task                         python             dag-test-bqz82-2879397570  6s
 ├─⚠ supplier                           do-suppliers
 │ ├─⚠ supplier-stuff(0:supplier_id:1)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:1)    python-subpoint    dag-test-bqz82-2627030665  6s
 │ │ ├─⚠ another-subpoint               main                                                    invalid character 'a' in literal true (expecting 'r')
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ ├─⚠ supplier-stuff(1:supplier_id:2)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:2)    python-subpoint    dag-test-bqz82-1446968660  7s
 │ │ ├─⚠ another-subpoint               main                                                    invalid character 'a' in literal true (expecting 'r')
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ ├─⚠ supplier-stuff(2:supplier_id:3)  do-supplier-tasks
 │ │ ├─✔ checkpoint(0:supplier_id:3)    python-subpoint    dag-test-bqz82-1623956195  7s
 │ │ ├─⚠ another-subpoint               main                                                    invalid character 'a' in literal true (expecting 'r')
 │ │ └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 │ └─⚠ supplier-stuff(3:supplier_id:4)  do-supplier-tasks
 │   ├─✔ checkpoint(0:supplier_id:4)    python-subpoint    dag-test-bqz82-3611620758  6s
 │   ├─⚠ another-subpoint               main                                                    invalid character 'a' in literal true (expecting 'r')
 │   └─⚠ subpoint                       main                                                    invalid character 'a' in literal true (expecting 'r')
 └─✔ second-task(0)                     main               dag-test-bqz82-1012186023  6s
```

So it looks like that either `when` is causing issues even for substeps where it's not used.
