### ISSUE TITLE
argo-server repeatable crash due to out of memory on big workflows

### ISSUE THREAD

**Issue by amitm02** [argoproj/argo-workflows#6000]
## Summary 

I've allocated argo-server (V3.1-rc7) 2.2GB of RAM.
When workflow reaches around ~6000 nodes, the Argo server crash with OOM.
After the crash, it keeps restarting due to OOM.
Using "watch" I was able to monitor the memory usage of argo-server from 10MB to around 1.4GB before it crashes.
I understand that argo-server will need more RAM for bigger workflows, but 2.2GB seems like a pretty big allocation. 

```
time="2021-05-25T10:20:50.474Z" level=info authModes="[server client]" baseHRef=/ managedNamespace=argo namespace=argo secure=true
time="2021-05-25T10:20:50.474Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-05-25T10:20:50.474Z" level=info msg="SSO disabled"
time="2021-05-25T10:20:50.486Z" level=info msg="Starting Argo Server" instanceID= version=v3.1.0-rc7
time="2021-05-25T10:20:50.486Z" level=info msg="Creating DB session"
time="2021-05-25T10:20:50.500Z" level=info msg="Node status offloading config" ttl=5m0s
time="2021-05-25T10:20:50.501Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-05-25T10:20:50.507Z" level=info msg="Argo Server started successfully on https://localhost:2746"
time="2021-05-25T10:25:50.471Z" level=info msg="Alloc=8184 TotalAlloc=18322 Sys=73553 NumGC=6 Goroutines=93"
time="2021-05-25T10:25:57.166Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=41.138 span.kind=server system=grpc
time="2021-05-25T10:25:57.168Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=21.007 span.kind=server system=grpc
time="2021-05-25T10:25:57.263Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=0.081 span.kind=server system=grpc
time="2021-05-25T10:25:57.396Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=132.886 span.kind=server system=grpc
time="2021-05-25T10:25:57.580Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=0.11 span.kind=server system=grpc
time="2021-05-25T10:26:15.762Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:15Z" grpc.time_ms=107.927 span.kind=server system=grpc
time="2021-05-25T10:26:16.158Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:15Z" grpc.time_ms=504.674 span.kind=server system=grpc
time="2021-05-25T10:26:16.160Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:15Z" grpc.time_ms=507.07 span.kind=server system=grpc
time="2021-05-25T10:26:16.266Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=92.15 span.kind=server system=grpc
time="2021-05-25T10:26:16.273Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=12.042 span.kind=server system=grpc
time="2021-05-25T10:26:16.358Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=90.825 span.kind=server system=grpc
time="2021-05-25T10:26:16.359Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=99.319 span.kind=server system=grpc
time="2021-05-25T10:26:16.360Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=100.189 span.kind=server system=grpc
time="2021-05-25T10:26:16.360Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=92.885 span.kind=server system=grpc
time="2021-05-25T10:26:16.361Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=94.709 span.kind=server system=grpc
time="2021-05-25T10:26:16.362Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=95.387 span.kind=server system=grpc
time="2021-05-25T10:26:16.365Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=92.359 span.kind=server system=grpc
time="2021-05-25T10:26:16.366Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=98.918 span.kind=server system=grpc
time="2021-05-25T10:26:16.366Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=DeleteWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=93.911 span.kind=server system=grpc
time="2021-05-25T10:26:16.608Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:25:57Z" grpc.time_ms=18921.3 span.kind=server system=grpc
time="2021-05-25T10:26:16.612Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=4.624 span.kind=server system=grpc
time="2021-05-25T10:30:50.471Z" level=info msg="Alloc=21029 TotalAlloc=118745 Sys=74193 NumGC=15 Goroutines=100"
time="2021-05-25T10:35:50.471Z" level=info msg="Alloc=53995 TotalAlloc=2189725 Sys=143124 NumGC=106 Goroutines=100"
time="2021-05-25T10:40:50.471Z" level=info msg="Alloc=89586 TotalAlloc=6012167 Sys=211815 NumGC=209 Goroutines=100"
time="2021-05-25T10:45:50.471Z" level=info msg="Alloc=111260 TotalAlloc=9272606 Sys=347821 NumGC=262 Goroutines=100"
time="2021-05-25T10:46:45.693Z" level=info msg="finished streaming call with code Canceled" error="rpc error: code = Canceled desc = context canceled" grpc.code=Canceled grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:26:16Z" grpc.time_ms=1.228909e+06 span.kind=server system=grpc
time="2021-05-25T10:46:46.265Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-05-25T10:46:46Z" grpc.time_ms=13.126 span.kind=server system=grpc
time="2021-05-25T10:46:46.360Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-05-25T10:46:46Z" grpc.time_ms=0.082 span.kind=server system=grpc
time="2021-05-25T10:46:46.365Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-05-25T10:46:46Z" grpc.time_ms=2.369 span.kind=server system=grpc
time="2021-05-25T10:46:46.757Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-05-25T10:46:46Z" grpc.time_ms=0.07 span.kind=server system=grpc
time="2021-05-25T10:47:05.796Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:46:46Z" grpc.time_ms=19427.557 span.kind=server system=grpc
time="2021-05-25T10:50:50.560Z" level=info msg="Alloc=223668 TotalAlloc=16597930 Sys=1448338 NumGC=337 Goroutines=101"
time="2021-05-25T10:55:50.470Z" level=info msg="Alloc=170449 TotalAlloc=30753200 Sys=1448338 NumGC=504 Goroutines=101"
time="2021-05-25T11:00:50.471Z" level=info msg="Alloc=112543 TotalAlloc=45584482 Sys=1448338 NumGC=673 Goroutines=101"
time="2021-05-25T11:05:50.471Z" level=info msg="Alloc=58310 TotalAlloc=60018368 Sys=1448338 NumGC=837 Goroutines=101"
time="2021-05-25T11:10:50.471Z" level=info msg="Alloc=230839 TotalAlloc=74778864 Sys=1448338 NumGC=978 Goroutines=101"
time="2021-05-25T11:15:50.471Z" level=info msg="Alloc=272255 TotalAlloc=89222709 Sys=1448594 NumGC=1108 Goroutines=101"
time="2021-05-25T11:20:50.471Z" level=info msg="Alloc=278787 TotalAlloc=105610555 Sys=1448850 NumGC=1222 Goroutines=101"
time="2021-05-25T11:23:12.873Z" level=error msg="finished streaming call with code Unknown" error=EOF grpc.code=Unknown grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T10:47:06Z" grpc.time_ms=2.1667878e+06 span.kind=server system=grpc
time="2021-05-25T11:25:50.471Z" level=info msg="Alloc=11805 TotalAlloc=110634076 Sys=1448850 NumGC=1258 Goroutines=101"
time="2021-05-25T11:30:50.471Z" level=info msg="Alloc=11591 TotalAlloc=111472443 Sys=1448850 NumGC=1268 Goroutines=101"
time="2021-05-25T11:35:50.471Z" level=info msg="Alloc=12185 TotalAlloc=111475399 Sys=1448850 NumGC=1270 Goroutines=101"
time="2021-05-25T11:40:50.471Z" level=info msg="Alloc=11587 TotalAlloc=111478318 Sys=1448850 NumGC=1273 Goroutines=101"
time="2021-05-25T11:45:50.471Z" level=info msg="Alloc=25338 TotalAlloc=111556046 Sys=1448850 NumGC=1279 Goroutines=101"
time="2021-05-25T11:50:50.471Z" level=info msg="Alloc=69397 TotalAlloc=113618824 Sys=1448850 NumGC=1361 Goroutines=101"
time="2021-05-25T11:55:50.471Z" level=info msg="Alloc=123311 TotalAlloc=116972746 Sys=1448850 NumGC=1448 Goroutines=101"
time="2021-05-25T12:00:50.471Z" level=info msg="Alloc=214425 TotalAlloc=120155411 Sys=1449106 NumGC=1496 Goroutines=101"
time="2021-05-25T12:04:52.405Z" level=error msg="finished streaming call with code Internal" error="rpc error: code = Internal desc = an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding" grpc.code=Internal grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T11:23:18Z" grpc.time_ms=2.4941345e+06 span.kind=server system=grpc
time="2021-05-25T12:05:50.471Z" level=info msg="Alloc=274119 TotalAlloc=126366697 Sys=1449362 NumGC=1566 Goroutines=101"
time="2021-05-25T12:05:55.820Z" level=info msg="finished streaming call with code Canceled" error="rpc error: code = Canceled desc = context canceled" grpc.code=Canceled grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-05-25T12:04:52Z" grpc.time_ms=63396.02 span.kind=server system=grpc
time="2021-05-25T12:05:55.872Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-05-25T12:05:55Z" grpc.time_ms=11.872 span.kind=server system=grpc
time="2021-05-25T12:05:55.872Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-05-25T12:05:55Z" grpc.time_ms=2.451 span.kind=server system=grpc
```

```
Name:         argo-server-555db8fb54-46gtj
Namespace:    argo
Priority:     0
Node:         gke-argo-dev-pool-1-60041216-q1c6/10.128.15.197
Start Time:   Tue, 25 May 2021 13:20:46 +0300
Labels:       app=argo-server
              pod-template-hash=555db8fb54
Annotations:  <none>
Status:       Running
IP:           10.96.1.20
IPs:
  IP:           10.96.1.20
Controlled By:  ReplicaSet/argo-server-555db8fb54
Containers:
  argo-server:
    Container ID:  containerd://9fce6725641117e629ff7ea4bd56a3a1d4af497dce9ac6af69d03d6d1df51a76
    Image:         argoproj/argocli:v3.1.0-rc7
    Image ID:      docker.io/argoproj/argocli@sha256:2ed4251f5453a48d77efe6748776b2aed75907ee8dac65ada19738aa9a9581f7
    Port:          2746/TCP
    Host Port:     0/TCP
    Args:
      server
      --namespaced
      --auth-mode
      server
      --auth-mode
      client
    State:          Running
      Started:      Tue, 25 May 2021 15:06:31 +0300
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 25 May 2021 13:20:50 +0300
      Finished:     Tue, 25 May 2021 15:06:30 +0300
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     500m
      memory:  1600Mi
    Requests:
      cpu:      500m
      memory:   1600Mi
    Readiness:  http-get https://:2746/ delay=10s timeout=1s period=20s #success=1 #failure=3
    Environment:
      BASE_HREF:  /
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from argo-server-token-nfbsn (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  argo-server-token-nfbsn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  argo-server-token-nfbsn
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason   Age                   From     Message
  ----    ------   ----                  ----     -------
  Normal  Created  2m32s (x2 over 108m)  kubelet  Created container argo-server
  Normal  Started  2m32s (x2 over 108m)  kubelet  Started container argo-server
  Normal  Pulled   2m32s                 kubelet  Container image "argoproj/argocli:v3.1.0-rc7" already present on machine
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by amitm02** [comment]
UPDATE:
Refreshing the browser (url: http://<domain>:/workflows?limit=500), causes the memory spike and crash.
Here is the memory monitoring.

```
Tue May 25 16:40:26 IDT 2021        argo-server-555db8fb54-rwrzm           2m           15Mi            
Tue May 25 16:40:29 IDT 2021        argo-server-555db8fb54-rwrzm           2m           15Mi            
Tue May 25 16:40:31 IDT 2021        argo-server-555db8fb54-rwrzm           2m           15Mi            
Tue May 25 16:40:34 IDT 2021        argo-server-555db8fb54-rwrzm           2m           15Mi            
Tue May 25 16:40:36 IDT 2021        argo-server-555db8fb54-rwrzm           2m           15Mi       
-- browser refresh     
Tue May 25 16:40:39 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:41 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:44 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:46 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:48 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:51 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:53 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:56 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:40:58 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi          
Tue May 25 16:41:00 IDT 2021        argo-server-555db8fb54-rwrzm           59m          1350Mi     
-- OOM crash        
Tue May 25 16:41:03 IDT 2021        
Tue May 25 16:41:05 IDT 2021        
Tue May 25 16:41:08 IDT 2021        
Tue May 25 16:41:10 IDT 2021        
Tue May 25 16:41:12 IDT 2021        
Tue May 25 16:41:15 IDT 2021        
Tue May 25 16:41:17 IDT 2021        
Tue May 25 16:41:20 IDT 2021        
Tue May 25 16:41:22 IDT 2021        
Tue May 25 16:41:24 IDT 2021        
Tue May 25 16:41:27 IDT 2021        
Tue May 25 16:41:29 IDT 2021        
Tue May 25 16:41:32 IDT 2021        
Tue May 25 16:41:34 IDT 2021        argo-server-555db8fb54-rwrzm           31m          16Mi            
Tue May 25 16:41:37 IDT 2021        argo-server-555db8fb54-rwrzm           31m          16Mi            
Tue May 25 16:41:39 IDT 2021        argo-server-555db8fb54-rwrzm           31m          16Mi            
Tue May 25 16:41:42 IDT 2021        argo-server-555db8fb54-rwrzm           31m          16Mi  
```


```
Tue May 25 16:36:54 IDT 2021        argo-server-555db8fb54-rwrzm           273m         158Mi           
Tue May 25 16:36:57 IDT 2021        argo-server-555db8fb54-rwrzm           273m         158Mi           
Tue May 25 16:36:59 IDT 2021        argo-server-555db8fb54-rwrzm           273m         158Mi 
-- browser refresh           
Tue May 25 16:37:03 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:05 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:07 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:10 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:13 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:15 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:18 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:20 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:23 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:25 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:27 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:30 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi           
Tue May 25 16:37:32 IDT 2021        argo-server-555db8fb54-rwrzm           115m         717Mi      
-- OOM crash          
Tue May 25 16:37:36 IDT 2021        argo-server-555db8fb54-rwrzm           1m           16Mi            
Tue May 25 16:37:38 IDT 2021        argo-server-555db8fb54-rwrzm           1m           16Mi            
Tue May 25 16:37:40 IDT 2021        argo-server-555db8fb54-rwrzm           1m           16Mi            
Tue May 25 16:37:43 IDT 2021        argo-server-555db8fb54-rwrzm           1m           16Mi 
```

**Comment by alexec** [comment]
This sounds like a memory leak. 

Can you confirm if you've tested this in v3.0 and found the same issue?

**Comment by amitm02** [comment]
We believe so, but I can not confirm 100%. 
Pre 3.1 we had many other issues with big workflows, the server did crash, but I'm can not confirm it was due to the same reason. 
Our current workflow relies heavily on 3.1 features so I can not simply run it on 3.0.

**Comment by alexec** [comment]
@amitm02 if I create a debug build, could I ask you to test and capture some heap dumps?

**Comment by amitm02** [comment]
Sure

**Comment by alexec** [comment]
Excellent.

Can you run `argoproj/argocli:dev-pprof`. You'll need to enable the profiling tool by using `ARGO_SERVER_PPROF=true`. E.g. `ARGO_SERVER_PPROF=true ./dist/argo server`. 

You should see this printed in the logs:

```
starting server for pprof or :6060, see https://golang.org/pkg/net/http/pprof/
```


I'd like to see the "heap" and "allocs" profiles, both when the server is using not very much memory and when it is using a lot. Capture many if you like.

```
go tool pprof -svg http://localhost:6060/debug/pprof/heap
go tool pprof -svg http://localhost:6060/debug/pprof/allocs
```

Change "svg" to "png" if you have any problem (pngs are less detailed, but still useful).

These two should show any leaks.

**Comment by DO-YardenG** [comment]
Hi,
Attaching profile svgs for the following:
- normal load (53MB mem usage by server)
- medium load (580MB mem usage)
- High load (1288MB mem usage, right before crashing with OOM exceptions)
- crash load (1GB+ mem, after server pods starts OOM killed and restarts, which happens over and over again

[argo-issue-6000-svgs.zip](https://github.com/argoproj/argo-workflows/files/6546936/argo-issue-6000-svgs.zip)

**Comment by alexec** [comment]
Thank you. I can tell from the dump that you are using node offloading, and this appears to be one potential cause, can I ask:

* Is `ALWAYS_OFFLOAD_NODE_STATUS=true`. This is a debug flag and should NEVER be set.
* How many workflows do you have?
* How many nodes does each workflow have?
* How are you listing/watching workflows? Via the UI, or are you using the API?

**Comment by DO-YardenG** [comment]
Thanks for the swift reply!

- We do not use the `ALWAYS_OFFLOAD_NODE_STATUS` flag at all 
(we do use `nodeStatusOffLoad: true` on our controller's configmap)
- Currently we only ever run a single workflow at a time (though 1-2 may still be present in the DB. 
can confirm it happens even if the DB is empty)
- Generally around 8K-25K nodes. 
the crash happens at around 4K-7K nodes completed with our current memory allocation of 2.2GB ram. 
(Each workflow we got the crash with has around 16-24 steps, looping over these steps a few thousand times)
- We've generally only seen these crashes happen when watching through the UI (`https://<SERVER>/workflows` URL). 
refreshing the URL tends to trigger the issue.

**Comment by alexec** [comment]
@DO-YardenG  My current hypothesis is JSON marshaling of offloaded data is causing your problem.

I've just pushed a fix to `dev-pprof`. This fix only "hydrates" workflows ("hydration" is when we go to the database to get the offloaded nodes) if those nodes will actually be returned via the API. 

It can take up to 1h for your new image (`argoproj/argocli:dev-pprof`) to be published. 

Could I please ask you to test to see if it fixed your issue? Please capture pprof output again.

**Comment by DO-YardenG** [comment]
Of course, i'll update once i finish testing!  :thumbsup:

**Comment by DO-YardenG** [comment]
It does indeed fix the issue as far as i can tell! 😃 
We are not getting any high memory peaks (nothing above 600MB), and the server does not crash consistently anymore while refreshing the UI. (it does still crash once in a while, but not for the same actions, i'll try and debug it separately.)

attached are the heap/allocs SVG's from our latest testing:
- no-load (22MB, no workflows running)
- normal load (35MB, 1 workflow running )
- peak-load (around 600MB peak usage, while refreshing the UI )

[argo-issue-6000-svgs-2705.zip](https://github.com/argoproj/argo-workflows/files/6555114/argo-issue-6000-svgs-2705.zip)

**Comment by alexec** [comment]
Awesome. Thank you for testing.
