### ISSUE TITLE
pod logs UI bug on  v3.2.0

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#6947]
when using argo v3.2.0, dynamic logs on pods do not display on UI until pods are finished, it keeps as `Waiting for data...`  without resolution

**Comment by sarabala1979** [comment]
Fixed in v3.2.1

**Comment by alexec** [comment]
You can revert behaviour using `POD_NAMES=v1`

**Comment by alexec** [comment]
It should be possible to fix this by finding wherever `LocalVarPodName` is in the codebase, and checking it uses `PodName` not `NodeID`.

**Comment by gabrieltomasrizzo** [comment]
I am using version 3.2.4 and I still have the same problem, only the logs are shown after the pods are finished.
During execution I only see "waiting for data".
![image](https://user-images.githubusercontent.com/36966227/147100762-2319a17b-7a63-48a4-9205-7f54300338b7.png)

I have tested it with various workflows including the python example shown here in this thread.
