### ISSUE TITLE
3.4rc2 - Archived Workflows are left-aligned

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-workflows#9433]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
Upgraded from 3.3.9 to 3.4rc2 and the archived workflows are now all left-aligned and hard to navigate as a result. I couldn't really give you a detailed screenshot, but I hope you get the idea:
![image](https://user-images.githubusercontent.com/69461449/186611222-8b177c54-2f8c-471f-8aa0-1fe3c24f8086.png)

What version are you running? 3.4rc2
Firefox 103 on macOS 12.5.1

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by terrytangyuan** [comment]
Should be fixed via #9439.

**Comment by tim-sendible** [comment]
This is NOT fixed in rc3.

**Comment by terrytangyuan** [comment]
@sarabala1979 I noticed that rc3 is released. What is the process to include commits to cherry-pick to rc releases?

**Comment by tim-sendible** [comment]
This remains an issue in rc4

**Comment by rajaie-sg** [comment]
This issue still exists in 3.4 https://github.com/argoproj/argo-workflows/issues/9614
